name: build-irods
on: [push, pull_request]
jobs:
  build:
    name: ubuntu job
    runs-on: ubuntu-20.04
    container: 'ubuntu:18.04'
    steps:
      - name: Public IP
        run: curl ifconfig.me.
      - name: Install git > v2.18 for Checkout
        run:  |
              apt-get update
              apt-get install -qq software-properties-common
              add-apt-repository ppa:git-core/ppa
              apt-get update
              apt-get install -qq git
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get Public IP
        run:  |
              apt-get install -qq sudo dnsutils apt-transport-https ca-certificates
              dig +short myip.opendns.com @resolver1.opendns.com
      - name: Install Dependencies
        run:  |
              sudo apt-get update -qq
              sudo apt-get install -qq wget curl g++ make python-dev help2man unixodbc libcurl4-gnutls-dev libbz2-dev zlib1g-dev libpam0g-dev libssl-dev libxml2-dev unixodbc-dev python-psutil super odbc-postgresql libkrb5-dev
      - name: Install libstdc++6
        run:  |
              sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
              sudo apt-get update -qq
              sudo apt-get install -qq libstdc++6
      - name: Install iRODS Externals
        run:  |
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | sudo apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods-unstable.list
              sudo apt-get update -qq
              sudo apt-get install -qq irods-externals-*
