name: build-irods
on: [push, pull_request]
jobs:
  build:
    name: ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: Install iRODS Externals
        run: |
              apt update
              apt-get traceroute -y
              traceroute -4 unstable.irods.org
              traceroute -4 yandex.ru
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/renci-irods-unstable.list
              apt-get update -qq
              apt-get install -qq irods-externals-*
