name: build-irods
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install iRODS Externals
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 20
          command: |
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | sudo apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods-unstable.list
              sudo apt-get update -qq
              sudo apt-get install -qq irods-externals-*
