name: build-irods
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:16.04', 'ubuntu:18.04']
    steps:
      - name: Install iRODS Externals
        run: |
              apt update
              apt-get install wget gnupg lsb-release -y
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/renci-irods-unstable.list
              apt-get update -qq
              apt-get install -qq irods-externals-*
