name: build-irods
on: [push, pull_request]
jobs:
  build:
    name: ubuntu job
    runs-on: ubuntu-18.04
    steps:
      - name: Public IP
        run: curl ifconfig.me.
      - name: Install iRODS Externals
        run: |
              sudo mv /etc/apt/sources.list /tmp/sources.list.backup
              sudo mv /etc/apt/sources.list.d /tmp/sources.list.d.backup
              sudo mkdir /etc/apt/sources.list.d
              sudo cp /usr/share/doc/apt/examples/sources.list /etc/apt/sources.list
              sudo apt update
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | sudo apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods-unstable.list
              sudo apt-get update -qq
              sudo apt-get install -qq irods-externals-*
